apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learnlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Infinia-Technology/NotebookLm-Learnlab.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: learnlab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
