apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: learnlab
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/infinia-technology/learnlab-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: learnlab-config
            - secretRef:
                name: learnlab-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
