apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: learnlab
type: kubernetes.io/dockerconfigjson
data:
  # Generate this value with:
  #
  #   kubectl create secret docker-registry ghcr-secret \
  #     --docker-server=ghcr.io \
  #     --docker-username=<your-github-username> \
  #     --docker-password=<your-github-PAT-with-read:packages-scope> \
  #     --namespace=learnlab \
  #     --dry-run=client -o yaml
  #
  # Then paste the generated .dockerconfigjson value below.
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibmF2bmVldC1zaGFoaTAwIiwicGFzc3dvcmQiOiJnaHBfSnhQeEcyZ2tKdEp2OU5SUWprSDRLN055TkRNQnVzM1VqSEFCIiwiYXV0aCI6ImJtRjJibVZsZEMxemFHRm9hVEF3T21kb2NGOUtlRkI0UnpKbmEwcDBTblk1VGxKUmFtdElORXMzVG5sT1JFMUNkWE16VldwSVFVST0ifX19
